kotlin.code.style=official
org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=512m -XX:+UseG1GC -XX:MaxGCPauseMillis=200
kotlin.mpp.enableCInteropCommonization=true
kotlin.mpp.applyDefaultHierarchyTemplate=false
android.useAndroidX=true

# Build performance
org.gradle.parallel=true
org.gradle.caching=true
kotlin.native.ignoreDisabledTargets=true
